// <auto-generated />
using System;
using System.Net;
using ArrControl.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArrControl.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ArrControlDbContext))]
    [Migration("20260716145616_MissingSortIndex")]
    partial class MissingSortIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Activity.HistoryItemEntity", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_key");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("correlation_key")
                        .IsFixedLength();

                    b.Property<string>("DownloadId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("download_id");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<string>("MediaProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("media_provider_key");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_kind");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.HasKey("InstanceId", "ProviderKey")
                        .HasName("pk_history_items");

                    b.HasIndex("InstanceId", "EventAt")
                        .HasDatabaseName("ix_history_items_instance_id_event_at");

                    b.HasIndex("InstanceId", "CorrelationKey", "EventAt")
                        .HasDatabaseName("ix_history_items_instance_id_correlation_key_event_at");

                    b.ToTable("history_items", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Activity.QueueItemEntity", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_key");

                    b.Property<DateTimeOffset?>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.Property<string>("CorrelationKey")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("correlation_key")
                        .IsFixedLength();

                    b.Property<string>("DownloadClient")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("download_client");

                    b.Property<string>("DownloadId")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("download_id");

                    b.Property<DateTimeOffset?>("EstimatedCompletionAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("estimated_completion_at");

                    b.Property<string>("Indexer")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("indexer");

                    b.Property<string>("MediaProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("media_provider_key");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Protocol")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("protocol");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_kind");

                    b.Property<long>("RemainingBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("remaining_bytes");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<string>("TrackedState")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracked_state");

                    b.Property<string>("TrackedStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("tracked_status");

                    b.HasKey("InstanceId", "ProviderKey")
                        .HasName("pk_queue_items");

                    b.HasIndex("InstanceId", "CorrelationKey")
                        .HasDatabaseName("ix_queue_items_instance_id_correlation_key");

                    b.ToTable("queue_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_queue_items_remaining", "remaining_bytes >= 0");

                            t.HasCheckConstraint("ck_queue_items_size", "size_bytes >= 0");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Automation.JobRunEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempts");

                    b.Property<DateTimeOffset>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("lease_owner");

                    b.Property<Guid?>("LeaseToken")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_token");

                    b.Property<DateTimeOffset?>("LeaseUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_until");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uuid")
                        .HasColumnName("schedule_id");

                    b.Property<DateTimeOffset>("ScheduledFor")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_for");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("ScheduleId", "ScheduledFor")
                        .IsUnique()
                        .HasDatabaseName("ux_job_runs_schedule_id_scheduled_for");

                    b.HasIndex("State", "AvailableAt", "LeaseUntil")
                        .HasDatabaseName("ix_job_runs_claim")
                        .HasFilter("completed_at IS NULL");

                    b.ToTable("job_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_job_runs_attempts_nonnegative", "attempts >= 0");

                            t.HasCheckConstraint("ck_job_runs_available_order", "available_at >= scheduled_for");

                            t.HasCheckConstraint("ck_job_runs_completion_order", "completed_at IS NULL OR (started_at IS NOT NULL AND completed_at >= started_at)");

                            t.HasCheckConstraint("ck_job_runs_lease_pair", "(lease_owner IS NULL AND lease_until IS NULL AND lease_token IS NULL AND last_heartbeat_at IS NULL) OR (lease_owner IS NOT NULL AND lease_until IS NOT NULL AND lease_token IS NOT NULL AND last_heartbeat_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_job_runs_state", "state IN ('pending', 'running', 'retry', 'succeeded', 'failed')");

                            t.HasCheckConstraint("ck_job_runs_state_completion", "(state IN ('succeeded', 'failed')) = (completed_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_job_runs_state_lease", "(state = 'running') = (lease_token IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Automation.ScheduleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Cron")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("cron");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<DateTimeOffset?>("LastEnqueuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_enqueued_at");

                    b.Property<string>("ScopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope_json");

                    b.Property<string>("ScopeKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope_key");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_schedules");

                    b.HasIndex("Type", "ScopeKey")
                        .IsUnique()
                        .HasDatabaseName("ux_schedules_type_scope_key")
                        .HasFilter("scope_key IS NOT NULL");

                    b.ToTable("schedules", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Automation.SyncCheckpointEntity", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Stream")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("stream");

                    b.Property<string>("Cursor")
                        .HasMaxLength(4096)
                        .HasColumnType("character varying(4096)")
                        .HasColumnName("cursor");

                    b.Property<DateTimeOffset>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_success_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstanceId", "Stream")
                        .HasName("pk_sync_checkpoints");

                    b.ToTable("sync_checkpoints", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.MediaEntityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<string>("CanonicalKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("canonical_kind");

                    b.Property<int?>("EpisodeNumber")
                        .HasColumnType("integer")
                        .HasColumnName("episode_number");

                    b.Property<string>("ExternalIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("external_ids_json");

                    b.Property<bool?>("HasFile")
                        .HasColumnType("boolean")
                        .HasColumnName("has_file");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean")
                        .HasColumnName("monitored");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_key");

                    b.Property<int?>("SeasonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("season_number");

                    b.Property<string>("SortTitle")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("sort_title")
                        .HasComputedColumnSql("lower(title)", true);

                    b.Property<DateTimeOffset?>("SourceAddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_added_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("title");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_media_entities");

                    b.HasIndex("InstanceId", "ProviderKey")
                        .IsUnique()
                        .HasDatabaseName("ux_media_entities_instance_id_provider_key");

                    b.HasIndex("SortTitle", "Id")
                        .HasDatabaseName("ix_media_entities_sort_title_id");

                    b.HasIndex("InstanceId", "CanonicalKind", "Monitored", "HasFile", "AvailableAt")
                        .HasDatabaseName("ix_media_entities_missing_projection");

                    b.ToTable("media_entities", null, t =>
                        {
                            t.HasCheckConstraint("ck_media_entities_episode_number", "episode_number IS NULL OR episode_number >= 0");

                            t.HasCheckConstraint("ck_media_entities_season_number", "season_number IS NULL OR season_number >= 0");

                            t.HasCheckConstraint("ck_media_entities_year", "year IS NULL OR year > 0");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.MissingItemEntity", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_key");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<bool>("Monitored")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("monitored");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstanceId", "ProviderKey")
                        .HasName("pk_missing_items");

                    b.HasIndex("Reason", "UpdatedAt")
                        .HasDatabaseName("ix_missing_items_reason_updated_at");

                    b.ToTable("missing_items", null, t =>
                        {
                            t.HasCheckConstraint("ck_missing_items_reason", "reason IN ('missing', 'not_available')");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.MissingSavedViewEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_json");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_missing_saved_views");

                    b.HasIndex("UserId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_missing_saved_views_user_id_name");

                    b.ToTable("missing_saved_views", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.ProviderItemEntity", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("provider_key");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("fingerprint")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("ParentProviderKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("parent_provider_key");

                    b.Property<string>("ProviderDataJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("provider_data_json");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_kind");

                    b.Property<string>("RawKind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("raw_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InstanceId", "ProviderKey")
                        .HasName("pk_provider_items");

                    b.HasIndex("InstanceId", "RawKind")
                        .HasDatabaseName("ix_provider_items_instance_id_raw_kind");

                    b.ToTable("provider_items", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.CredentialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Ciphertext")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("ciphertext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<int>("KeyVersion")
                        .HasColumnType("integer")
                        .HasColumnName("key_version");

                    b.Property<byte[]>("Nonce")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("nonce");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("purpose");

                    b.Property<byte[]>("Tag")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("tag");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_credentials");

                    b.HasIndex("InstanceId", "Purpose")
                        .IsUnique()
                        .HasDatabaseName("ux_credentials_instance_id_purpose");

                    b.ToTable("credentials", null, t =>
                        {
                            t.HasCheckConstraint("ck_credentials_ciphertext_not_empty", "octet_length(ciphertext) > 0");

                            t.HasCheckConstraint("ck_credentials_key_version", "key_version > 0");

                            t.HasCheckConstraint("ck_credentials_nonce_length", "octet_length(nonce) = 12");

                            t.HasCheckConstraint("ck_credentials_tag_length", "octet_length(tag) = 16");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AllowPrivateNetworkAccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("allow_private_network_access");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("base_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("enabled");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<bool>("TlsVerificationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("tls_verification_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_service_instances");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_service_instances_group_id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_service_instances_name");

                    b.ToTable("service_instances", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.InstanceGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_instance_groups");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_instance_groups_name");

                    b.ToTable("instance_groups", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.ProviderCapabilityEntity", b =>
                {
                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("Capability")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("capability");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Supported")
                        .HasColumnType("boolean")
                        .HasColumnName("supported");

                    b.HasKey("InstanceId", "Capability")
                        .HasName("pk_provider_capabilities");

                    b.ToTable("provider_capabilities", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Health.HealthIncidentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<Guid?>("AcknowledgedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("acknowledged_by_user_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("group_key")
                        .IsFixedLength();

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("ProviderKind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("provider_kind");

                    b.Property<string>("RemediationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remediation_url");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<Guid?>("SnoozedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("snoozed_by_user_id");

                    b.Property<DateTimeOffset?>("SnoozedUntil")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("snoozed_until");

                    b.HasKey("Id")
                        .HasName("pk_health_incidents");

                    b.HasIndex("AcknowledgedByUserId")
                        .HasDatabaseName("ix_health_incidents_acknowledged_by_user_id");

                    b.HasIndex("SnoozedByUserId")
                        .HasDatabaseName("ix_health_incidents_snoozed_by_user_id");

                    b.HasIndex("InstanceId", "GroupKey")
                        .IsUnique()
                        .HasDatabaseName("ux_health_incidents_instance_id_group_key");

                    b.HasIndex("InstanceId", "ResolvedAt", "LastSeenAt")
                        .HasDatabaseName("ix_health_incidents_instance_state_seen");

                    b.ToTable("health_incidents", null, t =>
                        {
                            t.HasCheckConstraint("ck_health_incidents_resolution_order", "resolved_at IS NULL OR resolved_at >= first_seen_at");

                            t.HasCheckConstraint("ck_health_incidents_seen_order", "last_seen_at >= first_seen_at");

                            t.HasCheckConstraint("ck_health_incidents_severity", "severity IN ('ok','notice','warning','error','unknown')");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Health.HealthIncidentSourceEntity", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uuid")
                        .HasColumnName("incident_id");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("source_key")
                        .IsFixedLength();

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Message")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("message");

                    b.Property<int>("ProviderIssueId")
                        .HasColumnType("integer")
                        .HasColumnName("provider_issue_id");

                    b.Property<string>("RemediationUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("remediation_url");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("source");

                    b.HasKey("IncidentId", "SourceKey")
                        .HasName("pk_health_incident_sources");

                    b.HasIndex("IncidentId", "Active")
                        .HasDatabaseName("ix_health_incident_sources_incident_id_active");

                    b.ToTable("health_incident_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_health_incident_sources_seen_order", "last_seen_at >= first_seen_at");

                            t.HasCheckConstraint("ck_health_incident_sources_severity", "severity IN ('ok','notice','warning','error','unknown')");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ClaimsVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("claims_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Issuer")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("issuer");

                    b.Property<DateTimeOffset?>("LastAuthenticatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_authenticated_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("subject");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_external_identities");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_external_identities_user_id");

                    b.HasIndex("Issuer", "Subject")
                        .IsUnique()
                        .HasDatabaseName("ux_external_identities_issuer_subject");

                    b.ToTable("external_identities", null, t =>
                        {
                            t.HasCheckConstraint("ck_external_identities_claims_version_nonnegative", "claims_version >= 0");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityRoleEntity", b =>
                {
                    b.Property<Guid>("ExternalIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_identity_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ExternalIdentityId", "RoleId")
                        .HasName("pk_external_identity_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_external_identity_roles_role_id");

                    b.ToTable("external_identity_roles", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.IdentityBootstrapStateEntity", b =>
                {
                    b.Property<short>("Id")
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    b.Property<Guid?>("AdminUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("admin_user_id");

                    b.Property<DateTimeOffset>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.HasKey("Id")
                        .HasName("pk_identity_bootstrap_state");

                    b.HasIndex("AdminUserId")
                        .HasDatabaseName("ix_identity_bootstrap_state_admin_user_id");

                    b.ToTable("identity_bootstrap_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_identity_bootstrap_state_singleton", "id = 1");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.OidcSessionContextEntity", b =>
                {
                    b.Property<Guid>("TokenFamilyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("ExternalIdentityId")
                        .HasColumnType("uuid")
                        .HasColumnName("external_identity_id");

                    b.Property<string>("ProtectedIdToken")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)")
                        .HasColumnName("protected_id_token");

                    b.HasKey("TokenFamilyId")
                        .HasName("pk_oidc_session_contexts");

                    b.HasIndex("ExternalIdentityId")
                        .HasDatabaseName("ix_oidc_session_contexts_external_identity_id");

                    b.ToTable("oidc_session_contexts", null, t =>
                        {
                            t.HasCheckConstraint("ck_oidc_session_contexts_expiration", "expires_at > created_at");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.PermissionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_permissions_code");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_roles_normalized_name");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.RolePermissionEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("locale");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("password_hash");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_users_normalized_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.UserRoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("InstanceGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_group_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_roles");

                    b.HasIndex("InstanceGroupId")
                        .HasDatabaseName("ix_user_roles_instance_group_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_user_roles_role_id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_roles_user_id_role_id_global")
                        .HasFilter("instance_group_id IS NULL");

                    b.HasIndex("UserId", "RoleId", "InstanceGroupId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_roles_user_id_role_id_instance_group_id")
                        .HasFilter("instance_group_id IS NOT NULL");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.UserSessionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AccessExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("access_expires_at");

                    b.Property<byte[]>("AccessTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("access_token_hash");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasDefaultValue("local")
                        .HasColumnName("authentication_method");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<byte[]>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("refresh_token_hash");

                    b.Property<Guid?>("ReplacedBySessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("replaced_by_session_id");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid>("TokenFamilyId")
                        .HasColumnType("uuid")
                        .HasColumnName("token_family_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_sessions");

                    b.HasIndex("AccessTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_access_token_hash");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_refresh_token_hash");

                    b.HasIndex("ReplacedBySessionId")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_replaced_by_session_id")
                        .HasFilter("replaced_by_session_id IS NOT NULL");

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_user_sessions_user_id_expires_at");

                    b.HasIndex(new[] { "TokenFamilyId" }, "user_sessions_active_token_family")
                        .IsUnique()
                        .HasDatabaseName("ux_user_sessions_active_token_family_id")
                        .HasFilter("revoked_at IS NULL");

                    b.HasIndex(new[] { "TokenFamilyId" }, "user_sessions_token_family_lookup")
                        .HasDatabaseName("ix_user_sessions_token_family_id");

                    b.ToTable("user_sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_sessions_access_expiration", "access_expires_at > created_at AND access_expires_at <= expires_at");

                            t.HasCheckConstraint("ck_user_sessions_access_token_hash_length", "octet_length(access_token_hash) = 32");

                            t.HasCheckConstraint("ck_user_sessions_authentication_method", "authentication_method IN ('local', 'oidc')");

                            t.HasCheckConstraint("ck_user_sessions_expiration", "expires_at > created_at");

                            t.HasCheckConstraint("ck_user_sessions_last_used_at", "last_used_at IS NULL OR last_used_at >= created_at");

                            t.HasCheckConstraint("ck_user_sessions_refresh_token_hash_length", "octet_length(refresh_token_hash) = 32");

                            t.HasCheckConstraint("ck_user_sessions_replacement", "replaced_by_session_id IS NULL OR replaced_by_session_id <> id");

                            t.HasCheckConstraint("ck_user_sessions_replacement_requires_revocation", "replaced_by_session_id IS NULL OR revoked_at IS NOT NULL");

                            t.HasCheckConstraint("ck_user_sessions_revoked_at", "revoked_at IS NULL OR revoked_at >= created_at");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.AuditEventEntity", b =>
                {
                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("action");

                    b.Property<string>("ActorIdentifier")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("actor_identifier");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("actor_type");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("correlation_id");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("outcome");

                    b.Property<string>("ScopeJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scope_json");

                    b.Property<string>("SummaryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("summary_json");

                    b.HasKey("OccurredAt", "Id")
                        .HasName("pk_audit_events");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_events_correlation_id");

                    b.HasIndex("Action", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_action_occurred_at");

                    b.HasIndex("ActorUserId", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_actor_user_id_occurred_at");

                    b.HasIndex("Outcome", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_outcome_occurred_at");

                    b.HasIndex("ActorIdentifier", "Action", "Outcome", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_login_account_throttle");

                    b.HasIndex("IpAddress", "Action", "Outcome", "OccurredAt")
                        .HasDatabaseName("ix_audit_events_login_ip_throttle");

                    b.ToTable("audit_events", (string)null);
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.OperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<bool>("CancellationRequested")
                        .HasColumnType("boolean")
                        .HasColumnName("cancellation_requested");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("DryRun")
                        .HasColumnType("boolean")
                        .HasColumnName("dry_run");

                    b.Property<DateTimeOffset>("IdempotencyExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("idempotency_expires_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("request_hash")
                        .IsFixedLength();

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("route");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasIndex("State", "CreatedAt")
                        .HasDatabaseName("ix_operations_state_created_at");

                    b.HasIndex("ActorUserId", "Route", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_operations_actor_route_idempotency_key");

                    b.ToTable("operations", null, t =>
                        {
                            t.HasCheckConstraint("ck_operations_state", "state IN ('pending','running','succeeded','partial','failed','cancelled')");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.OperationTargetEntity", b =>
                {
                    b.Property<Guid>("OperationId")
                        .HasColumnType("uuid")
                        .HasColumnName("operation_id");

                    b.Property<Guid>("InstanceId")
                        .HasColumnType("uuid")
                        .HasColumnName("instance_id");

                    b.Property<string>("TargetKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("target_key");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("error_code");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("state");

                    b.HasKey("OperationId", "InstanceId", "TargetKey")
                        .HasName("pk_operation_targets");

                    b.HasIndex("InstanceId", "State")
                        .HasDatabaseName("ix_operation_targets_instance_id_state");

                    b.ToTable("operation_targets", null, t =>
                        {
                            t.HasCheckConstraint("ck_operation_targets_state", "state IN ('pending','running','succeeded','failed','cancelled','skipped')");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.OutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("last_error_code");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.HasIndex("NextAttemptAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_unpublished")
                        .HasFilter("published_at IS NULL");

                    b.ToTable("outbox_messages", null, t =>
                        {
                            t.HasCheckConstraint("ck_outbox_messages_attempt_count_nonnegative", "attempt_count >= 0");
                        });
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Activity.HistoryItemEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_history_items_service_instances_instance_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Activity.QueueItemEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_queue_items_service_instances_instance_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Automation.JobRunEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Automation.ScheduleEntity", "Schedule")
                        .WithMany("JobRuns")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_job_runs_schedules_schedule_id");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Automation.SyncCheckpointEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sync_checkpoints_service_instances_instance_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.MediaEntityEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Catalog.ProviderItemEntity", "ProviderItem")
                        .WithOne("MediaEntity")
                        .HasForeignKey("ArrControl.Infrastructure.Persistence.Catalog.MediaEntityEntity", "InstanceId", "ProviderKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_media_entities_provider_items_instance_provider_key");

                    b.Navigation("ProviderItem");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.MissingItemEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Catalog.ProviderItemEntity", "ProviderItem")
                        .WithOne("MissingItem")
                        .HasForeignKey("ArrControl.Infrastructure.Persistence.Catalog.MissingItemEntity", "InstanceId", "ProviderKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_missing_items_provider_items_instance_provider_key");

                    b.Navigation("ProviderItem");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.MissingSavedViewEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_missing_saved_views_users_user_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.ProviderItemEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_items_service_instances_instance_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.CredentialEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", "Instance")
                        .WithMany("Credentials")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credentials_service_instances_instance_id");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceGroupEntity", "Group")
                        .WithMany("Instances")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_service_instances_instance_groups_group_id");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.ProviderCapabilityEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", "Instance")
                        .WithMany("Capabilities")
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_provider_capabilities_service_instances_instance_id");

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Health.HealthIncidentEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("AcknowledgedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_health_incidents_users_acknowledged_by_user_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_incidents_service_instances_instance_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("SnoozedByUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_health_incidents_users_snoozed_by_user_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Health.HealthIncidentSourceEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Health.HealthIncidentEntity", "Incident")
                        .WithMany("Sources")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_health_incident_sources_health_incidents_incident_id");

                    b.Navigation("Incident");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identities_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityRoleEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityEntity", "ExternalIdentity")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("ExternalIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identity_roles_external_identities_external_identity_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.RoleEntity", "Role")
                        .WithMany("ExternalIdentityAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_external_identity_roles_roles_role_id");

                    b.Navigation("ExternalIdentity");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.IdentityBootstrapStateEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", "AdminUser")
                        .WithMany()
                        .HasForeignKey("AdminUserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_identity_bootstrap_state_users_admin_user_id");

                    b.Navigation("AdminUser");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.OidcSessionContextEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityEntity", "ExternalIdentity")
                        .WithMany("SessionContexts")
                        .HasForeignKey("ExternalIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_oidc_session_contexts_external_identities_external_identity_id");

                    b.Navigation("ExternalIdentity");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.RolePermissionEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.PermissionEntity", "Permission")
                        .WithMany("Roles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.RoleEntity", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.UserRoleEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceGroupEntity", "InstanceGroup")
                        .WithMany()
                        .HasForeignKey("InstanceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_user_roles_instance_groups_instance_group_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.RoleEntity", "Role")
                        .WithMany("UserAssignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_roles_role_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_users_user_id");

                    b.Navigation("InstanceGroup");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.UserSessionEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserSessionEntity", "ReplacedBySession")
                        .WithMany()
                        .HasForeignKey("ReplacedBySessionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_user_sessions_user_sessions_replaced_by_session_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_sessions_users_user_id");

                    b.Navigation("ReplacedBySession");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.AuditEventEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", "ActorUser")
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_events_users_actor_user_id");

                    b.Navigation("ActorUser");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.OperationEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Identity.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operations_users_actor_user_id");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.OperationTargetEntity", b =>
                {
                    b.HasOne("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", null)
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_operation_targets_service_instances_instance_id");

                    b.HasOne("ArrControl.Infrastructure.Persistence.Operations.OperationEntity", "Operation")
                        .WithMany("Targets")
                        .HasForeignKey("OperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operation_targets_operations_operation_id");

                    b.Navigation("Operation");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Automation.ScheduleEntity", b =>
                {
                    b.Navigation("JobRuns");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Catalog.ProviderItemEntity", b =>
                {
                    b.Navigation("MediaEntity")
                        .IsRequired();

                    b.Navigation("MissingItem");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.InstanceEntity", b =>
                {
                    b.Navigation("Capabilities");

                    b.Navigation("Credentials");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Connections.InstanceGroupEntity", b =>
                {
                    b.Navigation("Instances");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Health.HealthIncidentEntity", b =>
                {
                    b.Navigation("Sources");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.ExternalIdentityEntity", b =>
                {
                    b.Navigation("RoleAssignments");

                    b.Navigation("SessionContexts");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.PermissionEntity", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.RoleEntity", b =>
                {
                    b.Navigation("ExternalIdentityAssignments");

                    b.Navigation("Permissions");

                    b.Navigation("UserAssignments");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Identity.UserEntity", b =>
                {
                    b.Navigation("ExternalIdentities");

                    b.Navigation("RoleAssignments");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("ArrControl.Infrastructure.Persistence.Operations.OperationEntity", b =>
                {
                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
