/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSystemStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Issues a CSRF token in both the response and the `__Host-arrcontrol_csrf` Secure, host-only, Path=/, SameSite cookie. Send the value in `X-CSRF-Token` on authentication mutations. */
        get: operations["getAuthCsrf"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns the authenticated user's current effective permissions. Grants are evaluated from the database for this request and must not be cached in the session cookie. */
        get: operations["getCurrentAuthorization"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** @description Replaces the authenticated user's UI locale and IANA timezone preference. The locale must be one of the shipped catalogs. */
        put: operations["updateCurrentUserPreferences"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["loginLocal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshLocalSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotently revokes the identified session family and clears local authentication cookies. */
        post: operations["logoutLocal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Reports whether OIDC is enabled without exposing provider credentials. */
        get: operations["getOidcStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Starts an OIDC Authorization Code + PKCE flow. The provider returns to the exact non-API callback `/auth/oidc/callback`; a successful callback issues ArrControl's opaque session cookies. */
        get: operations["loginOidc"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/oidc/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Idempotently revokes the local family and clears cookies before redirecting an OIDC-authenticated session through Authentik RP-initiated logout. If the protected logout context is unavailable, only the local redirect is performed. */
        post: operations["logoutOidc"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorization/permissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists the immutable permission catalog. Requires a global `authorization.manage` grant. */
        get: operations["listAuthorizationPermissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorization/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists system and custom roles. Requires a global `authorization.manage` grant. */
        get: operations["listAuthorizationRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorization/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        /** @description Gets one system or custom role. Requires a global `authorization.manage` grant. */
        get: operations["getAuthorizationRole"];
        /** @description Idempotently creates or replaces a custom role at the supplied ID. System roles are immutable. Requires a global `authorization.manage` grant and CSRF validation. */
        put: operations["upsertAuthorizationRole"];
        post?: never;
        /** @description Deletes a custom role and its assignments. System roles are immutable. Requires a global `authorization.manage` grant and CSRF validation. */
        delete: operations["deleteAuthorizationRole"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorization/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists users available for manual role assignment. Requires a global `authorization.manage` grant. */
        get: operations["listAuthorizationUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorization/users/{userId}/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        /** @description Lists only the user's manual global and instance-group role assignments. Requires a global `authorization.manage` grant. */
        get: operations["listUserRoleAssignments"];
        /** @description Idempotently replaces the complete set of manual role assignments for the user. OIDC-owned assignments are not changed. Requires a global `authorization.manage` grant and CSRF validation. */
        put: operations["replaceUserRoleAssignments"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authorization/instance-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists instance groups available as manual assignment scopes. Requires a global `authorization.manage` grant. */
        get: operations["listAuthorizationInstanceGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists instances visible through a global or instance-group-scoped `instances.read` grant. Scope filtering is applied in the database; ungrouped instances require a global grant. */
        get: operations["listInstances"];
        put?: never;
        /** @description Creates a provider configuration in a scope where the caller has `instances.manage`. Private-network access and disabled TLS verification are explicit per-instance choices. Requires CSRF validation. */
        post: operations["createInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        /** @description Gets one instance and its persisted capability observations when visible through `instances.read`; out-of-scope instances are returned as not found. */
        get: operations["getInstance"];
        /** @description Replaces one instance configuration. Moving between groups requires `instances.manage` in both old and new scopes. Connection-affecting changes invalidate prior capabilities. Requires CSRF validation. */
        put: operations["updateInstance"];
        post?: never;
        /** @description Deletes the instance and cascades its credentials and capabilities. Requires `instances.manage` in its scope and CSRF validation. */
        delete: operations["deleteInstance"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Performs a redirect-free, proxy-free, DNS-revalidated and address-pinned probe, then atomically replaces persisted capability observations. Contract-tested HTTP adapters read only their declared write-only credentials and call typed, version-checked status/health endpoints; kinds without an adapter receive only a credential-free generic transport probe. Requires `instances.manage` in the target scope and CSRF validation. */
        post: operations["probeInstance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instance-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists instance groups. Requires a global `instances.manage` grant. */
        get: operations["listInstanceGroups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instance-groups/{instanceGroupId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceGroupId: components["parameters"]["InstanceGroupId"];
            };
            cookie?: never;
        };
        get?: never;
        /** @description Idempotently creates or renames an instance group. Requires global `instances.manage` and CSRF validation. */
        put: operations["upsertInstanceGroup"];
        post?: never;
        /** @description Deletes an empty instance group. Groups with instances must be emptied explicitly first. Requires global `instances.manage` and CSRF validation. */
        delete: operations["deleteInstanceGroup"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/credentials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists only write-only credential metadata for an instance visible through `instances.read`. Plaintext and encryption material are never returned. */
        get: operations["listInstanceCredentials"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/instances/{instanceId}/credentials/{purpose}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
                purpose: components["parameters"]["CredentialPurpose"];
            };
            cookie?: never;
        };
        get?: never;
        /** @description Creates or replaces a write-only credential using the target instance's effective `instances.manage` scope. Requires CSRF validation; the request is limited to 8 KiB. */
        put: operations["putInstanceCredential"];
        post?: never;
        /** @description Idempotently deletes one credential using the target instance's effective `instances.manage` scope. Requires CSRF validation. */
        delete: operations["deleteInstanceCredential"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a title/ID keyset page from the last complete local catalog snapshots. Results are always intersected with the caller's current `library.read` instance-group scopes. */
        get: operations["listMissing"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missing/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMissingSavedViews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/missing/views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        get?: never;
        put: operations["upsertMissingSavedView"];
        post?: never;
        delete: operations["deleteMissingSavedView"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listQueue"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Returns a durable publication waterline and the REST resources the caller must read before opening the event stream. Reading the snapshot first and the REST projections second prevents reconnect gaps. */
        get: operations["getLiveEventSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Streams redacted resource invalidations as SSE. Supply the snapshot cursor as the initial query cursor; browser reconnects use Last-Event-ID. An unknown or expired cursor yields a snapshot-required event and closes. */
        get: operations["streamLiveEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Queries the append-only audit timeline. Because authentication and system events have no instance scope, the complete query requires a global audit.read grant. */
        get: operations["listAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diagnostics/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Explicitly creates a strict-redaction support archive and audits the export. It never includes credentials, names, URLs, IP addresses, paths, media metadata, raw provider payloads, audit summaries, or stable instance/group UUIDs. */
        post: operations["exportDiagnostics"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/incidents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Lists durable provider health incident groups visible through the caller's instances.read scopes. Related sources remain attached to one stable group. */
        get: operations["listHealthIncidents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/incidents/{incidentId}/acknowledgement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** @description Acknowledges or unacknowledges one incident after enforcing tasks.execute against its current instance-group scope. */
        put: operations["setHealthIncidentAcknowledgement"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/incidents/{incidentId}/snooze": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        get?: never;
        /** @description Snoozes an incident for at most 30 days, or clears its snooze with null, after scoped tasks.execute authorization. */
        put: operations["setHealthIncidentSnooze"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startSearchOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/search/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Resolves a selected/instance/group/all scope against current authorization and currently available missing items without creating an operation. */
        post: operations["previewSearchOperation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operations/{operationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOperation"];
        put?: never;
        post?: never;
        delete: operations["cancelOperation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SystemStatus: {
            /** @constant */
            name: "ArrControl";
            /** @enum {unknown} */
            status: "ok" | "degraded";
            version?: string;
            /** Format: date-time */
            utc: string;
        };
        CsrfToken: {
            token: string;
        };
        LocalLogin: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        AuthSession: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            accessExpiresAt: string;
            /** Format: date-time */
            refreshExpiresAt: string;
            csrfToken: string;
        };
        OidcStatus: {
            enabled: boolean;
            loginUrl: string | null;
        };
        /** @enum {string} */
        PermissionCode: "instances.read" | "instances.manage" | "library.read" | "search.execute" | "queue.manage" | "tasks.execute" | "users.manage" | "audit.read" | "settings.manage" | "authorization.manage";
        PermissionDefinition: {
            code: components["schemas"]["PermissionCode"];
        };
        PermissionGrant: {
            code: components["schemas"]["PermissionCode"];
            /** @description When true */
            global: boolean;
            /** @description Sorted instance-group scopes when global is false. */
            instanceGroupIds: string[];
        };
        CurrentAuthorization: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            /** @enum {string} */
            authenticationMethod: "local" | "oidc";
            /** @enum {string} */
            locale: "en" | "de";
            /** @description IANA timezone identifier supported by the server. */
            timeZone: string;
            /** @description Effective grants sorted by permission code. */
            permissions: components["schemas"]["PermissionGrant"][];
        };
        UpdateUserPreferences: {
            /** @enum {string} */
            locale: "en" | "de";
            timeZone: string;
        };
        UserPreferences: {
            /** @enum {string} */
            locale: "en" | "de";
            timeZone: string;
        };
        AuthorizationRole: {
            /** Format: uuid */
            id: string;
            name: string;
            isSystem: boolean;
            /** @description Permission codes sorted ordinally. */
            permissions: components["schemas"]["PermissionCode"][];
        };
        UpsertAuthorizationRole: {
            name: string;
            permissions: components["schemas"]["PermissionCode"][];
        };
        AuthorizationUser: {
            /** Format: uuid */
            userId: string;
            /** Format: email */
            email: string;
            state: string;
        };
        RoleAssignmentInput: {
            /** Format: uuid */
            roleId: string;
            /**
             * Format: uuid
             * @description Null assigns the role globally.
             */
            instanceGroupId: string | null;
        };
        ReplaceRoleAssignments: {
            assignments: components["schemas"]["RoleAssignmentInput"][];
        };
        RoleAssignment: {
            /** Format: uuid */
            roleId: string;
            roleName: string;
            /** Format: uuid */
            instanceGroupId: string | null;
        };
        InstanceGroupSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        /** @enum {string} */
        CredentialPurpose: "api-key" | "username" | "password";
        WriteCredential: {
            /** @description Maximum is 4 */
            secret: string;
        };
        CredentialMetadata: {
            purpose: components["schemas"]["CredentialPurpose"];
            /** @constant */
            configured: true;
            /** Format: date-time */
            updatedAt: string;
        };
        /**
         * @description Configuration kinds are not a support claim; see the provider compatibility matrix for contract-tested adapters.
         * @enum {string}
         */
        InstanceKind: "bazarr" | "deluge" | "emby" | "jellyfin" | "jellyseerr" | "lidarr" | "nzbget" | "ombi" | "overseerr" | "plex" | "prowlarr" | "qbittorrent" | "radarr" | "readarr" | "sabnzbd" | "sonarr" | "transmission" | "whisparr";
        InstanceSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["InstanceKind"];
            /** Format: uri */
            baseUrl: string;
            enabled: boolean;
            /** Format: uuid */
            instanceGroupId: string | null;
            tlsVerificationEnabled: boolean;
            allowPrivateNetworkAccess: boolean;
            credentialsConfigured: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProviderCapability: {
            capability: string;
            supported: boolean;
            /** Format: date-time */
            observedAt: string;
        };
        InstanceDetails: {
            /** Format: uuid */
            id: string;
            name: string;
            kind: components["schemas"]["InstanceKind"];
            /** Format: uri */
            baseUrl: string;
            enabled: boolean;
            /** Format: uuid */
            instanceGroupId: string | null;
            tlsVerificationEnabled: boolean;
            allowPrivateNetworkAccess: boolean;
            capabilities: components["schemas"]["ProviderCapability"][];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        WriteInstance: {
            name: string;
            kind: components["schemas"]["InstanceKind"];
            /**
             * Format: uri
             * @description Absolute HTTP(S) URL without credentials
             */
            baseUrl: string;
            /** @default true */
            enabled: boolean;
            /** Format: uuid */
            instanceGroupId?: string | null;
            /**
             * @description Disabling verification is an explicit high-risk exception.
             * @default true
             */
            tlsVerificationEnabled: boolean;
            /**
             * @description Explicitly permits RFC1918 or IPv6 ULA targets; special/link-local/loopback ranges remain blocked.
             * @default false
             */
            allowPrivateNetworkAccess: boolean;
        };
        ConnectionProbe: {
            connected: boolean;
            /** @enum {string} */
            outcome: "connected" | "connection_timeout" | "tls_validation_failed" | "connection_failed" | "credential_missing" | "unreachable" | "tls_error" | "unauthorized" | "forbidden" | "rate_limited" | "unsupported_version" | "invalid_response" | "upstream_conflict" | "not_found" | "timeout" | "unknown";
            httpStatusCode: number | null;
            /** Format: date-time */
            observedAt: string;
            capabilities: components["schemas"]["ProviderCapability"][];
            providerVersion: string | null;
            healthIssues: components["schemas"]["ProviderHealthIssue"][] | null;
            rateLimit: components["schemas"]["ProviderRateLimit"] | null;
        };
        ProviderHealthIssue: {
            /** Format: int32 */
            id: number;
            source: string;
            /** @enum {string} */
            severity: "ok" | "notice" | "warning" | "error" | "unknown";
            message: string | null;
            /** Format: uri */
            wikiUrl: string | null;
        };
        ProviderRateLimit: {
            limit: number | null;
            remaining: number | null;
            /** Format: date-time */
            resetAt: string | null;
            /** @description Invariant .NET TimeSpan value */
            retryAfter: string | null;
        };
        WriteInstanceGroup: {
            name: string;
        };
        InstanceGroupDetails: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        /** @enum {string} */
        MissingKind: "movie" | "episode" | "album" | "book";
        /** @enum {string} */
        MissingReason: "missing" | "not_available";
        MissingFilter: {
            instanceIds: string[];
            kinds: components["schemas"]["MissingKind"][];
            reasons: components["schemas"]["MissingReason"][];
            search: string | null;
        };
        WriteMissingSavedView: {
            name: string;
            instanceIds?: string[];
            kinds?: components["schemas"]["MissingKind"][];
            /**
             * @default [
             *       "missing"
             *     ]
             */
            reasons: components["schemas"]["MissingReason"][];
            search?: string | null;
        };
        MissingSavedView: {
            /** Format: uuid */
            id: string;
            name: string;
            filter: components["schemas"]["MissingFilter"];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        MissingItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instanceId: string;
            instanceName: string;
            /** @enum {string} */
            providerKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr";
            providerKey: string;
            kind: components["schemas"]["MissingKind"];
            title: string;
            year: number | null;
            seasonNumber: number | null;
            episodeNumber: number | null;
            reason: components["schemas"]["MissingReason"];
            /** Format: date-time */
            availableAt: string | null;
            /** Format: date-time */
            sourceAddedAt: string | null;
            externalIds: {
                [key: string]: string;
            };
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            observedAt: string | null;
            stale: boolean;
        };
        MissingFreshness: {
            /** Format: uuid */
            instanceId: string;
            /** Format: date-time */
            observedAt: string | null;
            stale: boolean;
        };
        MissingPage: {
            items: components["schemas"]["MissingItem"][];
            nextCursor: string | null;
            freshness: components["schemas"]["MissingFreshness"][];
        };
        AggregatedQueueItem: {
            /** Format: uuid */
            instanceId: string;
            instanceName: string;
            /** @enum {string} */
            providerKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr" | "prowlarr" | "sabnzbd" | "nzbget" | "qbittorrent" | "transmission" | "deluge";
            providerKey: string;
            mediaProviderKey: string | null;
            title: string;
            status: string;
            trackedStatus: string;
            trackedState: string;
            protocol: string | null;
            /** Format: int64 */
            sizeBytes: number;
            /** Format: int64 */
            remainingBytes: number;
            /** Format: date-time */
            addedAt: string | null;
            /** Format: date-time */
            estimatedCompletionAt: string | null;
            downloadClient: string | null;
            indexer: string | null;
            correlatedHistoryCount: number;
            latestHistoryEvent: string | null;
            importFailure: components["schemas"]["ImportFailureClassification"] | null;
            /** Format: date-time */
            observedAt: string;
            stale: boolean;
        };
        AggregatedHistoryItem: {
            /** Format: uuid */
            instanceId: string;
            instanceName: string;
            /** @enum {string} */
            providerKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr" | "prowlarr" | "sabnzbd" | "nzbget" | "qbittorrent" | "transmission" | "deluge";
            providerKey: string;
            mediaProviderKey: string | null;
            title: string;
            eventType: string;
            /** Format: date-time */
            eventAt: string;
            queueCorrelated: boolean;
            importFailure: components["schemas"]["ImportFailureClassification"] | null;
            /** Format: date-time */
            observedAt: string;
            stale: boolean;
        };
        ImportFailureClassification: {
            /** @enum {string} */
            category: "download_client_unavailable" | "import_blocked" | "import_failed" | "import_retry_pending" | "upstream_error" | "import_pending" | "download_failed" | "download_ignored";
            /** @enum {string} */
            severity: "warning" | "error";
            ruleId: string;
            /** @description Localization key; the API does not synthesize a diagnosis from free text. */
            guidanceKey: string;
            /**
             * @description Remains false until a safe provider retry contract is implemented and tested.
             * @constant
             */
            retrySupported: false;
        };
        HealthIncidentSource: {
            /** Format: int32 */
            providerIssueId: number;
            source: string;
            /** @enum {string} */
            severity: "ok" | "notice" | "warning" | "error" | "unknown";
            /** @description Bounded raw source diagnostic; never included in audit summaries or default logs. */
            message: string | null;
            /**
             * Format: uri
             * @description Provider-supplied HTTP(S) remediation link.
             */
            remediationUrl: string | null;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            active: boolean;
        };
        HealthIncident: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            instanceId: string;
            instanceName: string;
            /** @enum {string} */
            providerKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr" | "prowlarr" | "bazarr" | "sabnzbd" | "nzbget" | "qbittorrent" | "transmission" | "deluge" | "plex" | "jellyfin" | "emby" | "overseerr" | "jellyseerr" | "ombi";
            /** @enum {string} */
            severity: "ok" | "notice" | "warning" | "error" | "unknown";
            /** Format: uri */
            remediationUrl: string | null;
            /** Format: date-time */
            firstSeenAt: string;
            /** Format: date-time */
            lastSeenAt: string;
            /** Format: date-time */
            resolvedAt: string | null;
            /** Format: date-time */
            acknowledgedAt: string | null;
            /** Format: uuid */
            acknowledgedByUserId: string | null;
            /** Format: date-time */
            snoozedUntil: string | null;
            /** Format: uuid */
            snoozedByUserId: string | null;
            stale: boolean;
            sources: components["schemas"]["HealthIncidentSource"][];
        };
        SetHealthAcknowledgement: {
            acknowledged: boolean;
        };
        SetHealthSnooze: {
            /**
             * Format: date-time
             * @description Future UTC timestamp no more than 30 days away; null clears the snooze.
             */
            snoozedUntil: string | null;
        };
        LiveSnapshot: {
            /** @constant */
            version: 1;
            /** @description Opaque publication waterline; `origin` when no event has been published. */
            cursor: string;
            /** Format: date-time */
            generatedAt: string;
            /** @description Authorized REST projections to reload before streaming from cursor. */
            resources: string[];
        };
        LiveEvent: {
            /** Format: uuid */
            id: string;
            type: string;
            /** @enum {string} */
            resource: "instances" | "missing" | "activity" | "health" | "operations" | "audit";
            /** Format: date-time */
            occurredAt: string;
            /** @description IDs already filtered to the current caller scope; empty for actor/global events. */
            instanceIds: string[];
        };
        AuditEvent: {
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            occurredAt: string;
            /** Format: uuid */
            actorUserId: string | null;
            actorType: string;
            actorIdentifier: string;
            action: string;
            /** @description Already-redacted structured audit scope. */
            scope: {
                [key: string]: unknown;
            };
            correlationId: string;
            outcome: string;
            /** @description Already-redacted structured audit summary; credentials are forbidden at write time. */
            summary: {
                [key: string]: unknown;
            };
            /** @description Source address captured after trusted-proxy processing. */
            ipAddress: string | null;
        };
        AuditPage: {
            items: components["schemas"]["AuditEvent"][];
            nextCursor: string | null;
        };
        DiagnosticsExportRequest: {
            /** @default 24 */
            lookbackHours: number;
            /** @default true */
            includeAudit: boolean;
        };
        /** @enum {string} */
        OperationState: "pending" | "running" | "succeeded" | "partial" | "failed" | "cancelled";
        /** @enum {string} */
        OperationTargetState: "pending" | "running" | "succeeded" | "failed" | "cancelled" | "skipped";
        OperationTarget: {
            /** Format: uuid */
            instanceId: string;
            targetKey: string;
            state: components["schemas"]["OperationTargetState"];
            errorCode: string | null;
            /** @description Bounded provider-independent result JSON serialized as a string. */
            resultJson: string | null;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
        };
        Operation: {
            /** Format: uuid */
            id: string;
            type: string;
            state: components["schemas"]["OperationState"];
            dryRun: boolean;
            cancellationRequested: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            startedAt: string | null;
            /** Format: date-time */
            completedAt: string | null;
            targets: components["schemas"]["OperationTarget"][];
        };
        /** @enum {string} */
        SearchScopeMode: "selected" | "instance" | "group" | "all";
        SearchRequest: {
            mode: components["schemas"]["SearchScopeMode"];
            mediaEntityIds?: string[];
            instanceIds?: string[];
            instanceGroupIds?: string[];
            /** @default false */
            dryRun: boolean;
        };
        SearchResolvedTarget: {
            /** Format: uuid */
            instanceId: string;
            /** @enum {string} */
            providerKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr";
            providerKey: string;
        };
        SearchPreviewInstance: {
            /** Format: uuid */
            instanceId: string;
            /** @enum {string} */
            providerKind: "sonarr" | "radarr" | "lidarr" | "readarr" | "whisparr";
            targetCount: number;
        };
        SearchScopePreview: {
            mode: components["schemas"]["SearchScopeMode"];
            targetCount: number;
            excludedCount: number;
            instances: components["schemas"]["SearchPreviewInstance"][];
            targets: components["schemas"]["SearchResolvedTarget"][];
        };
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            traceId: string;
            code: string;
        };
    };
    responses: {
        /** @description RFC 9457 problem details */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Authentication is required (`authentication_required`). */
        AuthenticationRequired: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The effective authorization does not grant access (`access_denied`). */
        AccessDenied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Access is denied (`access_denied`) or CSRF validation failed (`csrf_validation_failed`). */
        AuthorizationMutationForbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request is malformed or fails authorization validation (`invalid_request`, `role_id_invalid`, `role_name_invalid`, `role_permissions_invalid`, `user_id_invalid`, or `role_assignments_invalid`). */
        InvalidAuthorizationRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The role does not exist (`role_not_found`). */
        RoleNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The user does not exist (`user_not_found`). */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The user, role, or instance group does not exist (`user_not_found`, `role_not_found`, or `instance_group_not_found`). */
        AssignmentReferenceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A role name is already used, a system role is immutable, or the change would remove the last global manager (`role_name_conflict`, `system_role_immutable`, or `authorization_lockout`). */
        RoleMutationConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The change would remove the last active user with global authorization administration (`authorization_lockout`). */
        AuthorizationLockout: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The credential target, purpose, or secret is invalid (`credential_target_invalid`, `credential_purpose_invalid`, or `credential_secret_invalid`). */
        CredentialRequestInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The instance does not exist or is outside the caller scope (`instance_not_found`). */
        InstanceNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No valid active credential encryption key is configured (`credential_encryption_unavailable`). */
        CredentialEncryptionUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The instance input or resolved outbound target is invalid or blocked (`instance_target_invalid`, `instance_name_invalid`, `instance_kind_invalid`, `instance_base_url_invalid`, `instance_group_name_invalid`, `outbound_target_invalid`, `outbound_dns_failed`, or `outbound_address_blocked`). */
        InstanceRequestInvalid: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The instance group does not exist (`instance_group_not_found`). */
        InstanceGroupNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The instance name or identifier is already used (`instance_conflict`). */
        InstanceConflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        InstanceId: string;
        InstanceGroupId: string;
        CredentialPurpose: components["schemas"]["CredentialPurpose"];
        RoleId: string;
        UserId: string;
        /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
        CsrfToken: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Runtime status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    getAuthCsrf: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description CSRF token issued; the response must not be cached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfToken"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    getCurrentAuthorization: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current identity and effective permission scopes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentAuthorization"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
        };
    };
    updateCurrentUserPreferences: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserPreferences"];
            };
        };
        responses: {
            /** @description Preferences persisted; the response must not be cached */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["Problem"];
        };
    };
    loginLocal: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocalLogin"];
            };
        };
        responses: {
            /** @description Authenticated; rotating opaque access and refresh cookies were issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            413: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    refreshLocalSession: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session rotated; replacement access and refresh cookies were issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSession"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    logoutLocal: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session revoked or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            403: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    getOidcStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OIDC availability */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OidcStatus"];
                };
            };
        };
    };
    loginOidc: {
        parameters: {
            query?: {
                /** @description Local absolute-path URL used after successful authentication. */
                returnUrl?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to the configured OIDC authorization endpoint */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    logoutOidc: {
        parameters: {
            query?: {
                /** @description Local absolute-path URL used after logout. */
                returnUrl?: string;
            };
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local redirect or redirect to the discovered end-session endpoint */
            302: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
            500: components["responses"]["Problem"];
        };
    };
    listAuthorizationPermissions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permission catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PermissionDefinition"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    listAuthorizationRoles: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roles and their permission bundles */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationRole"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    getAuthorizationRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role and its permission bundle */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationRole"];
                };
            };
            400: components["responses"]["InvalidAuthorizationRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["RoleNotFound"];
        };
    };
    upsertAuthorizationRole: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpsertAuthorizationRole"];
            };
        };
        responses: {
            /** @description Existing custom role replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationRole"];
                };
            };
            /** @description Custom role created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationRole"];
                };
            };
            400: components["responses"]["InvalidAuthorizationRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            409: components["responses"]["RoleMutationConflict"];
        };
    };
    deleteAuthorizationRole: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                roleId: components["parameters"]["RoleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Custom role deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InvalidAuthorizationRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["RoleNotFound"];
            409: components["responses"]["RoleMutationConflict"];
        };
    };
    listAuthorizationUsers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Users */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthorizationUser"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    listUserRoleAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manual role assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"][];
                };
            };
            400: components["responses"]["InvalidAuthorizationRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["UserNotFound"];
        };
    };
    replaceUserRoleAssignments: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceRoleAssignments"];
            };
        };
        responses: {
            /** @description Complete resulting set of manual role assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"][];
                };
            };
            400: components["responses"]["InvalidAuthorizationRequest"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["AssignmentReferenceNotFound"];
            409: components["responses"]["AuthorizationLockout"];
        };
    };
    listAuthorizationInstanceGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceGroupSummary"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    listInstances: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authorized instances */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSummary"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    createInstance: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteInstance"];
            };
        };
        responses: {
            /** @description Instance created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetails"];
                };
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["InstanceGroupNotFound"];
            409: components["responses"]["InstanceConflict"];
        };
    };
    getInstance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetails"];
                };
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["InstanceNotFound"];
        };
    };
    updateInstance: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteInstance"];
            };
        };
        responses: {
            /** @description Instance updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceDetails"];
                };
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            /** @description Instance or target group not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            409: components["responses"]["InstanceConflict"];
        };
    };
    deleteInstance: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["InstanceNotFound"];
        };
    };
    probeInstance: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionProbe"];
                };
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["InstanceNotFound"];
        };
    };
    listInstanceGroups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance groups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceGroupDetails"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    upsertInstanceGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceGroupId: components["parameters"]["InstanceGroupId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteInstanceGroup"];
            };
        };
        responses: {
            /** @description Group updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceGroupDetails"];
                };
            };
            /** @description Group created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceGroupDetails"];
                };
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            /** @description Instance-group name conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    deleteInstanceGroup: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceGroupId: components["parameters"]["InstanceGroupId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Group deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["InstanceRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["InstanceGroupNotFound"];
            /** @description Instance group is still in use (`instance_group_in_use`). */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listInstanceCredentials: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instanceId: components["parameters"]["InstanceId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured credential purposes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialMetadata"][];
                };
            };
            400: components["responses"]["CredentialRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["InstanceNotFound"];
        };
    };
    putInstanceCredential: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceId: components["parameters"]["InstanceId"];
                purpose: components["parameters"]["CredentialPurpose"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteCredential"];
            };
        };
        responses: {
            /** @description Existing credential replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialMetadata"];
                };
            };
            /** @description Credential created */
            201: {
                headers: {
                    Location?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CredentialMetadata"];
                };
            };
            400: components["responses"]["CredentialRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["InstanceNotFound"];
            503: components["responses"]["CredentialEncryptionUnavailable"];
        };
    };
    deleteInstanceCredential: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                instanceId: components["parameters"]["InstanceId"];
                purpose: components["parameters"]["CredentialPurpose"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential deleted or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["CredentialRequestInvalid"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["InstanceNotFound"];
        };
    };
    listMissing: {
        parameters: {
            query?: {
                /** @description Opaque protected cursor bound to the normalized filter. */
                cursor?: string;
                limit?: number;
                /** @description Uses this user-owned saved filter; inline filters are ignored. */
                savedViewId?: string;
                instanceId?: string[];
                kind?: components["schemas"]["MissingKind"][];
                reason?: components["schemas"]["MissingReason"][];
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cursor page with per-source freshness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
            404: components["responses"]["Problem"];
        };
    };
    listMissingSavedViews: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User-owned saved views */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingSavedView"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    upsertMissingSavedView: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WriteMissingSavedView"];
            };
        };
        responses: {
            /** @description Saved view replaced */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingSavedView"];
                };
            };
            /** @description Saved view created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissingSavedView"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            409: components["responses"]["Problem"];
        };
    };
    deleteMissingSavedView: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                viewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved view deleted or already absent */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
        };
    };
    listQueue: {
        parameters: {
            query?: {
                instanceId?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated current queue with history correlation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregatedQueueItem"][];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    listHistory: {
        parameters: {
            query?: {
                instanceId?: string[];
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Aggregated recent history with current-queue correlation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AggregatedHistoryItem"][];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    getLiveEventSnapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Caller-specific snapshot recovery contract */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveSnapshot"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    streamLiveEvents: {
        parameters: {
            query?: {
                /** @description Initial cursor returned by getLiveEventSnapshot. */
                cursor?: string;
            };
            header?: {
                /** @description SSE reconnect cursor; takes precedence over the query cursor. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE events named changed, cursor, or snapshot-required; heartbeat comments are emitted while idle. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    listAuditEvents: {
        parameters: {
            query?: {
                /** @description Inclusive start; defaults to 30 days before the request. */
                from?: string;
                /** @description Inclusive end; defaults to request time. */
                to?: string;
                actorUserId?: string;
                /** @description Exact action code. */
                action?: string;
                /** @description Exact outcome code. */
                outcome?: string;
                /** @description Exact correlation identifier. */
                correlationId?: string;
                /** @description Protected filter-bound keyset cursor. */
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Descending audit page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditPage"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    exportDiagnostics: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiagnosticsExportRequest"];
            };
        };
        responses: {
            /** @description ZIP containing diagnostics.json */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
        };
    };
    listHealthIncidents: {
        parameters: {
            query?: {
                instanceId?: string[];
                includeResolved?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scoped health incident groups and preserved source details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthIncident"][];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    setHealthIncidentAcknowledgement: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetHealthAcknowledgement"];
            };
        };
        responses: {
            /** @description Updated health incident */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthIncident"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["Problem"];
        };
    };
    setHealthIncidentSnooze: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                incidentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetHealthSnooze"];
            };
        };
        responses: {
            /** @description Updated health incident */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthIncident"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["Problem"];
        };
    };
    startSearchOperation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Search or dry-run operation accepted/replayed */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            409: components["responses"]["Problem"];
        };
    };
    previewSearchOperation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Explicit resolved target preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchScopePreview"];
                };
            };
            400: components["responses"]["Problem"];
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AccessDenied"];
        };
    };
    getOperation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Actor-owned operation and per-target outcomes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            404: components["responses"]["Problem"];
        };
    };
    cancelOperation: {
        parameters: {
            query?: never;
            header: {
                /** @description Must exactly match the __Host-arrcontrol_csrf cookie. */
                "X-CSRF-Token": components["parameters"]["CsrfToken"];
            };
            path: {
                operationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancellation requested or terminal operation acknowledged */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operation"];
                };
            };
            401: components["responses"]["AuthenticationRequired"];
            403: components["responses"]["AuthorizationMutationForbidden"];
            404: components["responses"]["Problem"];
        };
    };
}
